import{a as L,S as v,i as n}from"./assets/vendor-C_7oAj77.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const f of o.addedNodes)f.tagName==="LINK"&&f.rel==="modulepreload"&&a(f)}).observe(document,{childList:!0,subtree:!0});function r(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(t){if(t.ep)return;t.ep=!0;const o=r(t);fetch(t.href,o)}})();const b="41070058-40428010ccfde7f145f4a0888",w="https://pixabay.com/api/";async function p(e,s=1,r=40){try{const a=await L.get(w,{params:{key:b,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:s,per_page:r}});return{images:a.data.hits,total:a.data.totalHits}}catch(a){return console.error("Error fetching images:",a),{images:[],total:0}}}const g=document.querySelector(".gallery"),S=new v(".gallery a");function y(e){const s=e.map(r=>`
    <a href="${r.largeImageURL}" class="gallery-item">
      <img src="${r.webformatURL}" alt="${r.tags}" />
      <div class="info">
        <p><span class="info-label">Likes</span> <span class="info-value">${r.likes}</span></p>
        <p><span class="info-label">Views</span> <span class="info-value">${r.views}</span></p>
        <p><span class="info-label">Comments</span> <span class="info-value">${r.comments}</span></p>
        <p><span class="info-label">Downloads</span> <span class="info-value">${r.downloads}</span></p>
      </div>
    </a>
  `).join("");g.insertAdjacentHTML("beforeend",s),S.refresh()}function q(){g.innerHTML=""}function E(){const e=document.querySelector(".gallery-item");return e?e.getBoundingClientRect().height:0}const h=document.getElementById("search-form"),I=document.querySelector(".gallery"),i=document.querySelector(".loader"),l=document.querySelector(".load-more");let c="",d=1;const u=40;let m=0;(!h||!I||!i||!l)&&console.error("One or more elements not found!");h.addEventListener("submit",async e=>{if(e.preventDefault(),c=e.target.elements["search-input"].value.trim(),!c){n.error({message:"Введіть запит!"});return}d=1,q(),i.classList.remove("hidden"),l.classList.add("hidden");try{const{images:s,total:r}=await p(c,d,u);m=r,s.length===0?n.error({message:"Sorry, no images found. Try again!"}):(y(s),m>u&&l.classList.remove("hidden"))}catch{n.error({message:"Error fetching images. Try again!"})}finally{i.classList.add("hidden")}});l.addEventListener("click",async()=>{d++,i.classList.remove("hidden");try{const{images:e}=await p(c,d,u);y(e),$(),document.querySelectorAll(".gallery-item").length>=m&&(l.classList.add("hidden"),n.info({message:"We're sorry, but you've reached the end of search results."}))}catch{n.error({message:"Error fetching images. Try again!"})}finally{i.classList.add("hidden")}});function $(){const e=E();window.scrollBy({top:e*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
